name: Deploy

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy to Dokku
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOKKU_HOST }}
          username: deploy
          key: ${{ secrets.DEPLOY_KEY }}
          script: sudo docker pull ghcr.io/margin-at/margin:latest && sudo dokku git:from-image margin ghcr.io/margin-at/margin:latest --force